### ISSUE TITLE
2. Versión responsive de la web

### ISSUE THREAD

**Issue by GitTher** [Adalab/project-promo-o-module-1-team-1#3]
Hacer la web para el resto de tamaños de pantalla (tablet, desktop)

**RESOURCES**
Images in different sizes

**Tasks**
- [ ]  Header - tablet version
- [ ]  Hero - tablet version
- [ ]  Who we are - tablet version
- [ ]  Strengths and weaknesses - tablet version
- [ ]  Adalabers cards - tablet version
- [ ]  Footer - tablet version
- [ ]  Header - desktop version
- [ ]  Hero - desktop version
- [ ]  Who we are - desktop version
- [ ]  Strengths and weaknesses - desktop version
- [ ]  Adalabers cards - desktop version
- [ ]  Footer - desktop version
- [ ]  Published online
